name: colors-helper-tools

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm ci
      - run: npm test

  login-npm:
    needs: build
    steps:
      - name: npm install pacakges
        run: npm install
      - name: build npm packages
        run: npm run build
      - name: try npm login
        run: npm login --registry=https://registry.npmjs.org/ --scope=@your-scope --always-auth

  publish-gpr:
    needs: login-npm
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
